# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Default

steps:
  - task: BrowserStackConfig@0
    inputs:
      BrowserStackServiceEndPoint: 'Test_browserstack'
  - task: BrowserStackTestReports@0 
  
  - script: |
      npm install
      npm run test
    displayName: 'npm install & test'
  
  - task: BrowserStackResults@1
    inputs:
      browserstackProduct: 'automate'
  - task: BrowserStackStopLocal@0